### ISSUE TITLE
Reorder fields in schema the same way as prisma db pull does

### ISSUE THREAD

**Issue by madebysid** [prisma/templates#45]
So that people doing it after repo creation do not see a diff.

**Comment by jasonkuhrt** [comment]
CC @janpio you might be interested in this one.

**Comment by janpio** [comment]
Note: You can not just run `db push` and `db pull` for all projects in the project on the same database, as `db push` does not make sure to migrate the fields into the correct order - you have (!) to start with an empty database each time to make sure you actually get the same result.
